dotnet/ml-api-docs

dotnet/xml/_filter.xml

Fixes https://github.com/dotnet/docs/issues/5260

ML filter changes

---

dotnet/xml/Microsoft.ML.Trainers/StochasticDualCoordinateAscentClassifier.xml

Applying feedback comment from https://github.com/dotnet/ml-api-docs/pull/27/#discussion_r203610376

adding missing comma

---

dotnet/xml/_filter.xml

Fixes https://github.com/dotnet/docs/issues/6542
[Internal review URL](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.data?view=ml-dotnet&branch=pr-en-us-28)

expose Microsoft.ML.Runtime.Data APIs

---

dotnet/docfx.json

add search scope

---

dotnet/docfx.json
dotnet/xml/Microsoft.ML.Models/OnnxConverter.xml

Update live from master

---

dotnet/xml/Microsoft.ML.Runtime.Data/HashJoin.xml

Remove Dracula Transform reference

---

dotnet/xml/Microsoft.ML.Models/OnnxConverter.xml

Update live with master

---

.openpublishing.publish.config.json

Cherry picking the configuration to reference cs files in the examples, so i can test the changes in the smoke-test-preview.

Cherry picking commit  d438c93b from master

---

dotnet/xml/_filter.xml
dotnet/xml/ns-Microsoft.Data.DataView.xml
dotnet/xml/ns-Microsoft.ML.Calibrator.xml
dotnet/xml/ns-Microsoft.ML.Data.xml
dotnet/xml/ns-Microsoft.ML.ImageAnalytics.xml
dotnet/xml/ns-Microsoft.ML.LightGBM.xml
dotnet/xml/ns-Microsoft.ML.SamplesUtils.xml
dotnet/xml/ns-Microsoft.ML.StaticPipe.xml
dotnet/xml/ns-Microsoft.ML.Trainers.xml
dotnet/xml/ns-Microsoft.ML.Transforms.xml
dotnet/xml/ns-Microsoft.ML.xml

Updating the filter.xml and adding namespace descriptions.

updating the filter and the namespace descriptions for ML.Net

---

dotnet/xml/ns-Microsoft.ML.Calibrators.xml
dotnet/xml/ns-Microsoft.ML.EntryPoints.xml
dotnet/xml/ns-Microsoft.ML.Trainers.FastTree.xml
dotnet/xml/ns-Microsoft.ML.Trainers.Recommender.xml
dotnet/xml/ns-Microsoft.ML.Transforms.TensorFlow.xml
dotnet/xml/ns-Microsoft.ML.Transforms.Text.xml
dotnet/xml/ns-Microsoft.ML.Transforms.TimeSeries.xml
dotnet/xml/ns-Microsoft.ML.xml

Adding namespace descriptions.

Adding namespace descriptions for more namespaces

---

dotnet/xml/FrameworksIndex/ml-dotnet-1.0.0.xml
dotnet/xml/Microsoft.ML.Data/MulticlassClassificationMetrics.xml
dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmTrainerBase`4+OptionsBase.xml
dotnet/xml/Microsoft.ML.Trainers/FieldAwareFactorizationMachineTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/KMeansTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/LbfgsMaximumEntropyMulticlassTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaLogisticRegressionBinaryTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaMulticlassTrainerBase`1.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaNonCalibratedBinaryTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaRegressionTrainer.xml
dotnet/xml/Microsoft.ML.Transforms.Image/ImageDataViewType.xml
dotnet/xml/Microsoft.ML/CustomMappingCatalog.xml
dotnet/xml/Microsoft.ML/DataOperationsCatalog.xml
dotnet/xml/Microsoft.ML/ImageEstimatorsCatalog.xml
dotnet/xml/index.xml

Rebuild API docs after change to version configuration

---

dotnet/xml/FrameworksIndex/ml-dotnet-1.0.0.xml
dotnet/xml/Microsoft.ML.Data/MulticlassClassificationMetrics.xml
dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmTrainerBase`4+OptionsBase.xml
dotnet/xml/Microsoft.ML.Trainers/FieldAwareFactorizationMachineTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/KMeansTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/LbfgsMaximumEntropyMulticlassTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaLogisticRegressionBinaryTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaMulticlassTrainerBase`1.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaNonCalibratedBinaryTrainer.xml
dotnet/xml/Microsoft.ML.Trainers/SdcaRegressionTrainer.xml
dotnet/xml/Microsoft.ML.Transforms.Image/ImageDataViewType.xml
dotnet/xml/Microsoft.ML/CustomMappingCatalog.xml
dotnet/xml/Microsoft.ML/DataOperationsCatalog.xml
dotnet/xml/Microsoft.ML/ImageEstimatorsCatalog.xml
dotnet/xml/index.xml

Rebuild API docs after change to version configuration (ML.NET 1.1.0)

---

.openpublishing.publish.config.json

Switch docs pipeline to SDP

---

.gitignore
dotnet/xml/Microsoft.ML/VisionCatalog.xml

Added Sample references for Vision Catalog

Added Sample references for Vision Catalog

---

dotnet/xml/index.xml

Fix index.xml

---

dotnet/docfx.json
dotnet/xml/ns-Microsoft.Extensions.ML.xml
dotnet/xml/ns-Microsoft.ML.Vision.xml

Add missing namespace descriptions, and update date

---

dotnet/xml/ns-Microsoft.Extensions.ML.xml
dotnet/xml/ns-Microsoft.ML.Vision.xml

Fix namespace descriptions (#129)

---

dotnet/xml/Microsoft.ML.Trainers/LdSvmTrainer.xml

Preview link: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.ldsvmtrainer.info?branch=pr-en-us-133&view=ml-dotnet

Fix xrefs for the LDSVM trainer

---

dotnet/docfx.json

Update with _products_ taxonomy . Added  URI - "https://authoring-docs-microsoft.poolparty.biz/devrel/08606f2f-3c25-4e53-8851-28888c60aeed"  corresponds to customer facing product name ML.NET
ML.NET
--

add products taxonomy URI

---

dotnet/docfx.json

Adds customer facing products taxonomy in the configuration. 
|Product Name(Label)| Taxonomy URI |
|---------|-----------|
|ML.NET| https://authoring-docs-microsoft.poolparty.biz/devrel/08606f2f-3c25-4e53-8851-28888c60aeed|

add products taxonomy URI (#150)

---

.openpublishing.publish.config.json

Renamed branch reference for ML.NET from master to main.

Renamed reference from master to main for ml.net

---

dotnet/docfx.json

…ice = dotnet-ml-api (#167)
Describe your changes here.

1/18 Publish for metadata update
